### ISSUE TITLE
Checklist for next meeting

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-gitctf-team4#5]
Before meeting,
- [x] Review `http` code for injection (https://github.com/dhuertas/http)

In meeting,
- [ ] Create our team's public key `team4.pub` and upload it

- [x] Discuss about three intended vulnerabilities

- [x] Fix gcc warning

- [ ] Discuss about unintended vulnerabilities
